### ISSUE TITLE
Error when using "HLS Stream" and "Microphone"

### ISSUE THREAD

**Issue by AiDreamerOoO** [cyberofficial/Synthalingua#107]
Please help me check if I have set the parameters incorrectly.
Microphone is displayed during use, and the computer displays "Access denied to the computer"
![1](https://github.com/cyberofficial/Synthalingua/assets/154967620/e26963dc-f68d-4f72-a922-91249737d88f)
![2](https://github.com/cyberofficial/Synthalingua/assets/154967620/c1cba09b-e7ea-420b-a596-f734722b81b1)

HLS Stream  Show this

![3](https://github.com/cyberofficial/Synthalingua/assets/154967620/b986a1fc-aa5d-45ab-9013-7c24dd6bd025)
![4](https://github.com/cyberofficial/Synthalingua/assets/154967620/530c67bb-0663-461b-ad34-815d75f0855c)

Thanks for the guidance

**Comment by AiDreamerOoO** [comment]
![image](https://github.com/cyberofficial/Synthalingua/assets/154967620/cdb72acf-0aa1-4b63-b3da-922c84e625c6)
There are also crazy errors here. Am I missing some software that has not been installed? Or is there something wrong with my parameter settings?

**Comment by cyberofficial** [comment]
Hello Thank you for making a report.

Question:
Are you trying to use HLS stream and Microphone at the same time?

Question:
Do you press "Generate" then Press "Run" ?

Question:
Can you show me files of download?
Do they look like this?
![image](https://github.com/cyberofficial/Synthalingua/assets/19499442/fd95dfa9-1e15-46bc-a22a-51cdb1a98dbe)


WinError2 = Folder "ffmpeg" not found, "ffmpeg_path.bat" Not found
![opera_yExzRgT6hi](https://github.com/cyberofficial/Synthalingua/assets/19499442/392d5168-a5a1-4c6e-b9b7-9135558a960b)

**Comment by AiDreamerOoO** [comment]
> 您好，感谢您提交报告。
> 
> 问题： 您是否尝试同时使用 HLS 流和麦克风？
> 
> 问题： 您按“生成”然后按“运行”吗？
> 
> 问题： 您能给我看一下下载的文件吗？ 它们看起来像这样吗？ ![图像](https://private-user-images.githubusercontent.com/19499442/342674839-fd95dfa9-1e15-46bc-a22a-51cdb1a98dbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNzA2NDIsIm5iZiI6MTcxOTM3MDM0MiwicGF0aCI6Ii8xOTQ5OTQ0Mi8zNDI2NzQ4MzktZmQ5NWRmYTktMWUxNS00NmJjLWEyMmEtNTFjZGIxYTk4ZGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDAyNTIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4Zjk3MmVlN2VlNDFhOGQxMjQ5NjQzZTAyMWEwNDQ2YzgyYjU0N2Q0MzY3OGNkNDU4YTI0OTNiNGMyZTFjNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QJqqJSxmldwD1ViDvosD7C449xaDS0yImGrE036OgoY)
> 
> WinError2 = 未找到文件夹“ffmpeg”，未找到“ffmpeg_path.bat” ![opera_yExzRgT6hi](https://private-user-images.githubusercontent.com/19499442/342675608-392d5168-a5a1-4c6e-b9b7-9135558a960b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNzA2NDIsIm5iZiI6MTcxOTM3MDM0MiwicGF0aCI6Ii8xOTQ5OTQ0Mi8zNDI2NzU2MDgtMzkyZDUxNjgtYTVhMS00YzZlLWI5YjctOTEzNTU1OGE5NjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDAyNTIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMjJmZmM4YzVkYTZjNDFkOWY2YTczNGIxZmExYTE3ZGE3M2U0MmM0OTBjOTFiZTFiZWI1Y2VlNGMzZjNmYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4-u7ql5o9T8ZqOfT0YTCMXrgW__IihKTIWpqm8GSAdk)

I clicked "Generate" first and then "Run"

The file is like this
![image](https://github.com/cyberofficial/Synthalingua/assets/154967620/bee406b2-c301-44c7-a1b9-830ea5dc3bb6)
![Uploading image.png…]()

**Comment by AiDreamerOoO** [comment]
I want to try both HLS stream and Microphone. What does it mean to try them at the same time? Isn't it a choice?

**Comment by AiDreamerOoO** [comment]
When using the microphone, the language is detected, but there seems to be no output. It also does not translate

![5](https://github.com/cyberofficial/Synthalingua/assets/154967620/2e00a2ce-fa1f-481d-9a0e-0144e5c119dc)
![6](https://github.com/cyberofficial/Synthalingua/assets/154967620/25a717b8-0777-4990-8c89-f6488064ff09)

**Comment by AiDreamerOoO** [comment]
Can you give me a detailed tutorial? It's really necessary for us novices. Thank you very much.

**Comment by cyberofficial** [comment]
You can run the program two times, three, as many as you want, if your computer can handle it.

You need to change Port Number for captions for each window to new number if more than one open.

Example:
HLS = Port Number 2000
Microphone = Port Number 2001

If HLS and Microphone = 2000 they both fight for port number = Bad
If HLS =  2000 Microphone = 2001 they do not bother each other = Good


Port can be any number From 1024 - 65535
Like This
![opera_CfD4E8tb6X](https://github.com/cyberofficial/Synthalingua/assets/19499442/bd9b60a3-c9ba-4c34-832c-f24bf7e6fab5)


Each Program running needs own caption window too

**Comment by cyberofficial** [comment]
> Can you give me a detailed tutorial? It's really necessary for us novices. Thank you very much.

Guide is under work still, I plan on making one after my next big update.

**Comment by cyberofficial** [comment]
> When using the microphone, the language is detected, but there seems to be no output. It also does not translate


Please make sure "Enable Secondary" is enabled. 
![image](https://github.com/cyberofficial/Synthalingua/assets/19499442/7d00d50f-f1e5-451f-9def-5665f471d370)

**Comment by AiDreamerOoO** [comment]
Thank you very much for your answer. There is one thing that needs to be improved. The C drive is always full.
![1719380558128](https://github.com/cyberofficial/Synthalingua/assets/154967620/82f2954c-90f8-4ace-ac8b-41dbb303687a)

**Comment by cyberofficial** [comment]
> Thank you very much for your answer. There is one thing that needs to be improved. The C drive is always full. ![1719380558128](https://private-user-images.githubusercontent.com/154967620/343022643-82f2954c-90f8-4ace-ac8b-41dbb303687a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODExNDMsIm5iZiI6MTcxOTM4MDg0MywicGF0aCI6Ii8xNTQ5Njc2MjAvMzQzMDIyNjQzLTgyZjI5NTRjLTkwZjgtNGFjZS1hYzhiLTQxZGJiMzAzNjg3YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQwNTQ3MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mN2U4NTIyMmFkMTliNTM5NDIxZTAxMTU3ZTVhMzc2Y2M5YjdlNjcwYWMyMjAxODgyYjkwNjU2YzA4YjM4YTI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sl5tzssc2GJYvom-_Zi9ezNgakDkuobqoFYwm076WR0)


Please Delete "temp" folder in program folder.
![explorer_9RhfNGCTeF](https://github.com/cyberofficial/Synthalingua/assets/19499442/8138b1ed-7657-4319-8e30-27a4e9f3774f)

That is only place where stuff is kept.

**Comment by AiDreamerOoO** [comment]
Yes, I deleted this several times.

**Comment by cyberofficial** [comment]
Please make sure to press "Windows key" + "C" in the console window this
will auto clean up the files.
