### ISSUE TITLE
System cannot find file specified 

### ISSUE THREAD

**Issue by riuneko** [cyberofficial/Synthalingua#115]
Heya, downloaded both the "alpha" and stable release portables today and have been running into this error on both:

`Traceback (most recent call last):
  File "transcribe_audio.py", line 869, in <module>
  File "transcribe_audio.py", line 466, in main
  File "subprocess.py", line 421, in check_output
  File "subprocess.py", line 503, in run
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1440, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
[7884] Failed to execute script 'transcribe_audio' due to unhandled exception!`

Git should be working fine and I've confirmed that an ffmpeg installation is on PATH (and running ffmpeg command in cmd prompt works), so I'm not entirely sure where this error is coming from. 

Device: Windows 10.0.19045 
Hardware: 5600X3D, 6700XT

**Comment by cyberofficial** [comment]
[WinError 2] Means it can not find FFMPEG with full feature set, you can obtain the full feature set ffmpeg through here https://github.com/cyberofficial/Synthalingua/issues/2#issuecomment-1491098222 

Most of the time people will download the minimum version of ffmpeg.

If you downloaded the Alpha version (Version 1.1-A4) from itch, it should come with the FFMPEG version that works and a batch file "ffmpeg_path.bat" that auto sets the path.

In the wrapper, in the command block section, can you make sure that it's called like this? The line should mention the batch file and where ever you saved the program at.

![image](https://github.com/user-attachments/assets/bef4fc41-c6d1-412d-8f80-3dbcc75fad33)

**Comment by riuneko** [comment]
I followed that comment to download ffmpeg initially so I definitely have the full version (140MB executables)

Grabbed the Alpha ver again to test - checking the program, it's calling the script with `call "C:\Users\...\Downloads\synthalingua-windows-alpha\ffmpeg_path.bat"`. Ran the batch manually as well. The path is there when checking in system environment variables, but is still giving the same error.

**Comment by cyberofficial** [comment]
Can you try getting this https://github.com/yt-dlp/yt-dlp/releases/download/2024.07.16/yt-dlp_win.zip 

and add to path? Even though it's a requirement that's packaged with the portable, maybe windows is not detecting it properly.

**Comment by riuneko** [comment]
Alright, seemed to get past that error + am now greeted with this one:

`Unexpected error loading m3u8 file: URL can't contain control characters. '/videoplayback?expire=1721522550&ei=FgWcZr_hOI_2j-8PseGVOA&ip=2605%3Aa601%3A55ab%3A4700%3A3d29%3Aa1fd%3Ae371%3Af871&id=o-AMzKuunVJjDR83SSDWXuK_VLq5DhqJiwNJMNVYlF0MSJ&itag=303&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=jS&mm=31%2C29&mn=sn-bvvbax4pcxg-5uas%2Csn-5ualdnze&ms=au%2Crdu&mv=m&mvi=2&pl=42&initcwndbps=835000&bui=AXc671KyZ9xaMFyK-4zesd5HEFUXpscTnd_OIs5hBF8w8kl77sIUw5PSg0lgDBvmNZtFzgUP_f7mgqqn&spc=NO7bAZD__NtA4bfD3YadJ1Nge8LOKRpXwsitWeCF_OwCMOrkJBsjUBuJeTPv&vprv=1&svpuc=1&mime=video%2Fwebm&ns=v1mNPHGwP0eGmIlwhidYXfMQ&rqh=1&gir=yes&clen=5438391647&dur=16231.999&lmt=1721465538045380&mt=1721500609&fvip=4&keepalive=yes&c=WEB&sefc=1&txp=730F224&n=ZVvhi8nhvw5lmw&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAM3pefjV9Q5ySSPton4TLXxYec5Q9wko4SLF2aUbQ4v-AiEA2kkNezguhXda7w5fYv8v4eu2B3Uwa5umK-kefz47qZc%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRQIgJ4TX6nnxRzPXL4yjfTUcG_bpoduiCmGC1HTco3x_Ft4CIQDora3m651rsYO6cDAd4xlkW5koH_qVJ-iMIiBzXnZDUw%3D%3D\nhttps://rr2---sn-bvvbax4pcxg-5uas.googlevideo.com/videoplayback?expire=1721522550&ei=FgWcZr_hOI_2j-8PseGVOA&ip=2605%3Aa601%3A55ab%3A4700%3A3d29%3Aa1fd%3Ae371%3Af871&id=o-AMzKuunVJjDR83SSDWXuK_VLq5DhqJiwNJMNVYlF0MSJ&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=jS&mm=31%2C29&mn=sn-bvvbax4pcxg-5uas%2Csn-5ualdnze&ms=au%2Crdu&mv=m&mvi=2&pl=42&initcwndbps=835000&bui=AXc671KyZ9xaMFyK-4zesd5HEFUXpscTnd_OIs5hBF8w8kl77sIUw5PSg0lgDBvmNZtFzgUP_f7mgqqn&spc=NO7bAZD__NtA4bfD3YadJ1Nge8LOKRpXwsitWeCF_OwCMOrkJBsjUBuJeTPv&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=v1mNPHGwP0eGmIlwhidYXfMQ&rqh=1&gir=yes&clen=267466852&dur=16232.021&lmt=1721467025361525&mt=1721500609&fvip=4&keepalive=yes&c=WEB&sefc=1&txp=7308224&n=ZVvhi8nhvw5lmw&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAM0YWy6ZzJKVgKico2aw3MlpZ_oFKrSk1UsMJp19itJLAiBdEFcU6UBid3d1NUDsMYLb6Al5Sy7F4qluaUZHvnVD4A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRQIgJ4TX6nnxRzPXL4yjfTUcG_bpoduiCmGC1HTco3x_Ft4CIQDora3m651rsYO6cDAd4xlkW5koH_qVJ-iMIiBzXnZDUw%3D%3D' (found at least '\n')`

**Comment by cyberofficial** [comment]
Can you provide me the livestream you are trying to use?

**Comment by riuneko** [comment]
Sure, that stream was https://www.youtube.com/watch?v=nHUz8FULa1U

**Comment by cyberofficial** [comment]
it seems like YouTube requires your login session.
https://github.com/cyberofficial/Synthalingua?tab=readme-ov-file#cookies

You'll need to export your youtube session in NetScape Format and save to the folder `cookies` where the wrapper is.

![opera_9fPgnpbIn3](https://github.com/user-attachments/assets/eef54a57-f15c-40a2-a80c-4cbeee7888b0)


As of right now, with out cookie file it doesn't work. When adding cookies file, it works.

**Comment by riuneko** [comment]
That seems to have done the trick, thank you!
Forgot to hit Generate again so snagged on that.

**Comment by cyberofficial** [comment]
Feel free to make another issue if you need more help!

**Comment by riuneko** [comment]
Didn't want to make a whole other issue since it's a small thing, it seems to be working but I'm only getting translations once every maybe minute or so. Is that just the CPU being too slow to handle the program?
I adjusted chunk size to 10

**Comment by cyberofficial** [comment]
The higher ram mode chosen + cpu opention, the slower it may be

You may be able to test your luck using windows WSL https://github.com/cyberofficial/Synthalingua/discussions/28 as it does work with AMD and ROCm, 

You'll need to do download from source though and load from command line, but you can always just use the wrapper command box and copy and paste stuff


https://rocm.docs.amd.com/projects/radeon/en/latest/docs/compatibility/wsl/wsl_compatibility.html
