### ISSUE TITLE
ffmpeg is being redownloaded every time

### ISSUE THREAD

**Issue by rassver** [cyberofficial/Synthalingua#121]
I have ffmpeg in my PATH set for a while already since I've been using it from before, it works in CMD, but when I use synthalingua it doesn't recognize it and redownloads the package every time. I have also tried adding it to the folder manually, I've tried multiple locations, but it's all the same: 
.../ffmpeg.exe 
.../bin/ffmpeg.exe
.../ffmpeg/ffmpeg.exe
.../ffmpeg/bin/ffmpeg.exe 

Fun thing, even after it downloads it by itself, if I close the program and then launch it again it proceeds to redownload it again.
Using the latest alpha version.
![image](https://github.com/user-attachments/assets/a7cc3f8f-a8cc-4b67-b6bd-a986e35d32cc)
![image](https://github.com/user-attachments/assets/bf97a462-ed89-4e5c-8f4e-1fcce4abf01c)
![image](https://github.com/user-attachments/assets/b88a9730-c752-43ba-9fa1-74bf65a4192d)
![image](https://github.com/user-attachments/assets/7138787f-b422-4d7d-a4b3-99318b7c3195)

**Comment by rassver** [comment]
Update: tried the latest "old but stable" version from itch, it doesn't have such a problem.

**Comment by cyberofficial** [comment]
I notice the special signs in the file paths, are you using powershell or command prompt?
Do you have another language being used?

**Comment by rassver** [comment]
> Do you have another language being used? I might be able to modify the script depending what is happening.
I am using Japanese system local.

Here is more screenshots of what is happening.
It doesn't find ffmpeg, then downloads the archive with it. Then, for some reason, it fails to extract the archive. After it fails, it just proceeds to continue as usual, and works despite allegedly not having ffmpeg, translations work as well.
![image](https://github.com/user-attachments/assets/a2bd0b2b-2176-43a9-8aac-6d620c785159)

![image](https://github.com/user-attachments/assets/7b1db6c9-bac5-472a-9f67-a8cac6ca5ecf)

Then after relaunching it repeats again.

**Comment by cyberofficial** [comment]
> I am using Japanese system local.

This is fine, I realized it's just showing \ as ¥ doesn't effect it.

The 7-zip thing might be an issue. I can't include it in my release as it conflicts with my licensing.

Though I can make a work around. I'll add something to where it'll ask if you have 7zip or ffmeg already installed. The method I have right now is meant to make everything work easily as a simple one click thing so anyone can easily run it. I'll make changes later in my day. As it's 07:00 AM for me and I just woken up.

Thank you for your reply and report. :)

**Comment by cyberofficial** [comment]
if the issue isn't fixed, please reopen. Thanks!
