### ISSUE TITLE
Request: allow users to change model location

### ISSUE THREAD

**Issue by tuppgallocapon** [cyberofficial/Synthalingua#135]
Hello!

Love Synthalingua, use it all the time.

Small QoL issue: the ai models uses up a ton of space on my tiny OS SDD. I was wondering if you could add a `--model_dir path/to/your/dir` option so users can specify where the model is saved, similar to the default whisper ai?

**Comment by cyberofficial** [comment]
Hello! This can definitely be done and added to the todo list!

I'm currently working off from github right now so it may look the project isn't going forward, but it is.

I'll be sure to add this issue in the next patch I have coming up. 

The models are saved to the current directory of where the program is running at, so if you are using the portable version you can always just move to different location. As for the people using source, I could see it being beneficial.

**Comment by cyberofficial** [comment]
Hello o/

Implementation of the Custom Model Directory will be released fairly soon!
As long with some minor patches 

`--model_dir` will be the argument for it, it will accept both linux/windows location format.
If you use the GUI, the GUI was also updated to allow easier setting of location in a new tab called "Model Settings". 
Ram size was also moved to that tab.
