### ISSUE TITLE
License Change from GPL v3 to AGPL v3

### ISSUE THREAD

**Issue by cyberofficial** [cyberofficial/Synthalingua#139]
Hello ✅ @DaniruKun , ✅ @Expletive , ✅ @Adenser , and ✅ @ffalcon31415 ,

I hope you're all doing well! I wanted to inform you about an important change regarding the Synthalingua project.

# License Change from GPL v3 to AGPL v3:
I’ve decided to change the license of the project from the GNU General Public License (GPL) v3 to the GNU Affero General Public License (AGPL) v3. The AGPL extends the copyleft protection to network use, meaning if the software is used over a network, the source code must still be made available. 

# Why the Change:
Since I'm prepping to have better networking support and expanding to support networking environments, this change is needed to make sure the integrity of the project stays known even in networking environments. This change also helps to ensure that Synthalingua remains open and that any improvements made while being used in network-based services are also shared with the community. This aligns with the project's goals of keeping the software open and available to all users, even in a SaaS or web service environment.

# What I Need from You:
Since you have contributed to the project even while small,, I still kindly ask for your approval to re-license your contributions under AGPL v3. If you’re okay with this change, please leave a comment here confirming your approval.

If you have any concerns or questions about the license change, feel free to let me know. I’m happy to discuss this further if needed.

# Timeline:
Please provide your response by `October 8th, 2024 {end of day UTC}` . If I don’t hear back from you by then, I’ll follow up one more time 
before making changes.

Thank you for your contributions and your time!

**Comment by ffalcon31415** [comment]
Sounds good. Thanks!

**Comment by Expletive** [comment]
Yeah, I'm fine with it.

**Comment by DaniruKun** [comment]
Is fine with me!

**Comment by cyberofficial** [comment]
Thanks for the replies!
