### ISSUE TITLE
--no_log / cant see any transcriptions/translations

### ISSUE THREAD

**Issue by OE3JGW** [cyberofficial/Synthalingua#149]
hello, 
when im using --no_log i can not see any transcriptions anymore. i thought i should only see the translations when using this argument.
see screenshots.
if im removing this argument, everything works fine. 

@echo off
cls
call "data_whisper\Scripts\activate.bat"
call ffmpeg_path.bat
python transcribe_audio.py --ram 12gb-v3 --microphone_enabled True --set_microphone 3 --translate --target_language en --no_log
pause

![image](https://github.com/user-attachments/assets/4ccafcf1-27f5-45f2-96f4-f379d4b869ac)

**Comment by cyberofficial** [comment]
Thanks for the report. I will look at this. I might've changed a line by accident regarding logging and debugging.

**Comment by cyberofficial** [comment]
Hello! Could you please download this file: https://github.com/cyberofficial/Synthalingua/blob/bleeding-under-work/transcribe_audio.py and replace it with the current one you have?

**Comment by OE3JGW** [comment]
this fixed the issue, thanks :)
sorry for the late reply!
