### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by NauFirefox** [cyberofficial/Synthalingua#2]
`[WinError 2] The system cannot find the file specified[WinError 2] The system cannot find the file specified[WinError 2] The system cannot find the file specified[WinError 2] The system cannot find the file specified[WinError 2] The system cannot find the file specified[WinError 2] The system cannot find the file specified[WinError 2] The system cannot find the file specified[WinError 2] The system cannot find the file specified`

I saw you chatting about this on the subreddit, but I also seem to be getting the same. 

Win 10. --ram 12gb --non_english --translate --device cpu

**Comment by cyberofficial** [comment]
Hello! Could you try this


Visit ffmpeg Website https://www.gyan.dev/ffmpeg/builds/

<img width="637" alt="parsecd_ZATuVbgPG3" src="https://user-images.githubusercontent.com/19499442/228987157-c9a097c2-2e9a-46d9-a017-2ae244776001.png">

Download ffmpeg

extract the file to any location
For me, i made a new folder on Drive C called bin, then made a folder called ffmpeg
<img width="632" alt="explorer_6Jw6wo94Jo" src="https://user-images.githubusercontent.com/19499442/228987514-37eceba5-9ed3-4f29-800b-ad4f06738b1e.png">

i then took the  contents from the 7z archive and placed them into the ffmpeg folder i made
<img width="408" alt="explorer_1SmEP0K8sd" src="https://user-images.githubusercontent.com/19499442/228987630-ba3df28f-53ef-494f-9d73-8b1418166d48.png">

Then open System Environment Settings

<img width="238" alt="a7k3MXl093" src="https://user-images.githubusercontent.com/19499442/228987242-71c07a62-f9b3-41a3-8bd7-14bbb0994bc8.png">

<img width="274" alt="parsecd_REQBkY3C0p" src="https://user-images.githubusercontent.com/19499442/228987742-b46208a7-49c4-4857-8247-7a8767632341.png">

<img width="771" alt="parsecd_wyvm9cxm7i" src="https://user-images.githubusercontent.com/19499442/228987851-38566a3a-511f-4790-a9ce-50702b1bc60b.png">

Click path, Edit, New, Then past in the location of the bin folder with the ffmpeg folder.
The bin folder should have 3 programs in
<img width="564" alt="explorer_t0F5uW8nVm" src="https://user-images.githubusercontent.com/19499442/228987971-db42f4d2-1459-4a68-b880-cb0ba9fcd1bf.png">


After that, relaunch the program and try again.

Let me know if this works

**Comment by NauFirefox** [comment]
That did it, i did a quick test speaking jp into the mic and it picked it up and translated perfectly.
