### ISSUE TITLE
System cannot find file specified 

### ISSUE THREAD

**Issue by Kazzy-chan** [cyberofficial/Synthalingua#24]
when opening livetranslation.bat, it loads the model and then awaits audio stream.

when it detects an audio stream the following error occurs:

[WinError 2] The system cannot find the file specified

here is the Info at the beginning:

You are already using the latest version.
Current version: 1.0.993
Using device: cuda
CUDA device name: NVIDIA GeForce GTX 1070
VRAM available: 8191.875 MB
Microphone set to: system default
Now using ram flag: 4gb

**Comment by cyberofficial** [comment]
Please look at the troubleshooting section here: https://github.com/cyberofficial/Synthalingua#:~:text=%5BWinError%202%5D%20The%20system%20cannot%20find%20the%20file%20specified%20Try%20this%20fix%3A%20%232%20(comment) 
try that

**Comment by Kazzy-chan** [comment]
this worked, thank you!!
