### ISSUE TITLE
Portable version missing packages?

### ISSUE THREAD

**Issue by Adenser** [cyberofficial/Synthalingua#35]
When trying to use portable version of Synthalingua-1.0.995 I have been hit with a error
[Errno 2] No such file or directory: 'C:\\Users\\Adenser\\AppData\\Local\\Temp\\_MEI768762\\whisper\\assets\\mel_filters.npz'
normal version of Synthalingua-1.0.995 doesn't have such issue.
![image](https://github.com/cyberofficial/Synthalingua/assets/39248856/4de6dfcd-d08f-4e48-b99a-8317dac9d718)

**Comment by cyberofficial** [comment]
Thanks for the report, to be clear you have ffmpeg installed and added to system path?

**Comment by Adenser** [comment]
![image](https://github.com/cyberofficial/Synthalingua/assets/39248856/e4941415-6cdb-4204-ad35-035f83e749c9)
Yes sir. Without that I wouldn't be able to run version from source code.

**Comment by cyberofficial** [comment]
Thank you, I will be pushing a new update later today (Eastern time around 5pm.)

I think I found the issue with it.

**Comment by cyberofficial** [comment]
I think I solved the issue, I will be uploading a new portable version soon for people to test

**Comment by cyberofficial** [comment]
New Portable version is now released [1.0.996](https://github.com/cyberofficial/Synthalingua/releases/tag/1.0.996) See if that fixes it for you.

**Comment by Adenser** [comment]
I can confirm that the portable version works as intended.

Thank you very much for fixing this problem. And thank you for all your time put into this project.

**Comment by cyberofficial** [comment]
You're welcome, thanks for reporting the issue :D
