### ISSUE TITLE
Explore using PyInstaller

### ISSUE THREAD

**Issue by DaniruKun** [cyberofficial/Synthalingua#4]
[PyInstaller](https://pyinstaller.org/en/stable/) is a pretty neat way to package and bundle existing Python applications.

This would be very useful for less technical desktop users, compared to the current automated, but still quite manual approach which requires manual setup of different dependencies.

**Comment by cyberofficial** [comment]
I will look into it!

**Comment by cyberofficial** [comment]
https://github.com/cyberofficial/Synthalingua/releases/tag/1.0.0

Will use for future releases.
