### ISSUE TITLE
[1.0.9978]Phrase Timeout needed with webhook to start the software

### ISSUE THREAD

**Issue by Adenser** [cyberofficial/Synthalingua#51]
![image](https://github.com/cyberofficial/Synthalingua/assets/39248856/325761c0-1d9c-46f0-8f04-b587ae4dcee1)

`Traceback (most recent call last):`
`  File "E:\BAU BAU\transcribe_audio.py", line 611, in <module>`
`    main()`
`  File "E:\BAU BAU\transcribe_audio.py", line 123, in main`
`    print(f"{red_text}WARNING{reset_text}: phrase_timeout is set to {args.phrase_timeout} seconds. This will cause the webhook to send multiple messages. Setting phrase_timeout to 1 second to avoid this.")`
`UnboundLocalError: local variable 'reset_text' referenced before assignment`

`--phrase_timeout 1` must be set manually in the initial flags if webhook flag is presented, otherwise it will crash the software 
This is a degradation from 1.0.9971 where such flag was not needed.

**Comment by cyberofficial** [comment]
Thank you for the report, issue was found and fixed, will be pushing an update to the main branch after CodeQL is done testing.
