### ISSUE TITLE
Everything runs but....

### ISSUE THREAD

**Issue by ZeChArtiahSaher** [cyberofficial/Synthalingua#65]
I get something along the lines of

```
Audio stream detected...
Given groups=1, weight of size [1280, 128, 3], expected input[1, 80, 3000] to have 128 channels, but got 80 channels instead
```

Args used:

```
python "transcribe_audio.py" --ram 12gb --non_english --translate --energy_threshold 250
```

However it works with 4gb model. 3090 rtx so not a vram issue

**Comment by cyberofficial** [comment]
Thanks for the report, I'll look into it.

**Comment by cyberofficial** [comment]
I may have found the issue, and will experiment with some fixes.

Are you using the [master](https://github.com/cyberofficial/Synthalingua/tree/master) branch?

**Comment by ZeChArtiahSaher** [comment]
Cloned master yesterday

**Comment by ZeChArtiahSaher** [comment]
yeah no , same thing on 3.10.9

**Comment by cyberofficial** [comment]
Are you using any sort of program or software for the microphone?

You'll need to make the script is designated to a microphone with the `--set_microphone #` command.

![opera_80vfVJMddW](https://github.com/cyberofficial/Synthalingua/assets/19499442/cbbf41a5-a2d8-4506-a7c2-a245cacd2df4)

Example `python "transcribe_audio.py" --ram 12gb --set_microphone 8  --non_english --translate` will set it to nvidia broadcast best results are lower IDs of the device you want.

**Comment by ZeChArtiahSaher** [comment]
I got a loopback off an ssl 2+ audio interface. I suspect it's not the problem cuz again, audio streaming works just fine with small/medium whisper models.

-------- Original Message --------

**Comment by ZeChArtiahSaher** [comment]
I got a loopback off an ssl 2+ audio interface. I suspect it's not the problem cuz again, audio streaming works just fine with small/medium whisper models.

**Comment by cyberofficial** [comment]
In your model's folder do you have `large-v2.pt` ?

**Comment by ZeChArtiahSaher** [comment]
Large-v3 actually so I'm suppose to be on v2?

**Comment by cyberofficial** [comment]
Could you download the[ latest dev build](https://github.com/cyberofficial/Synthalingua/tree/dev-testing) and see if this fixes the issue

**Comment by ZeChArtiahSaher** [comment]
yeah that fixes, also so much faster, idk if that's the model or just the branch

**Comment by cyberofficial** [comment]
Thanks for testing.
