### ISSUE TITLE
Problems/ some questions

### ISSUE THREAD

**Issue by coden965** [cyberofficial/Synthalingua#82]
![image](https://github.com/cyberofficial/Synthalingua/assets/77539068/c7cfccda-eeb2-4814-9ca3-4a00ddc2f6e2)

![image](https://github.com/cyberofficial/Synthalingua/assets/77539068/ddd27867-34b9-469c-8d47-fd0938822f60)

Im not sure where i went wrong i followed the installation instructions however these problems occured.

**Comment by cyberofficial** [comment]
Hello!

Few questions I have;

What Python version are you using?
Are you using nvidia or amd gpu?

are you running the script as admin or basic user? Please make sure to not run as admin if so.

**Comment by coden965** [comment]
Hello! Sadly I did just come off my pc, however I was not running it as an admin, I was using python 3.10 with an nvidia 3060

**Comment by cyberofficial** [comment]
Hello! Could you download this https://github.com/cyberofficial/Synthalingua/blob/a37c2e0771648132a31d75ed5e1ed60da5b9d3d4/requirements.txt file change and replace the `requirements.txt` file with this one?

**Comment by coden965** [comment]
Hello, i just did this sorry for the long wait. However it is spitting out errors for torch.

![image](https://github.com/cyberofficial/Synthalingua/assets/77539068/08bca50e-bfb6-47d0-8d52-4a3e1196efdc)

**Comment by cyberofficial** [comment]
Okay, 
since you have python installed

could you create a random folder anywhere and inside that folder run the command `python -m venv .env`

Then activate that environment with `.env\Scripts\activate`

With that try and run `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118` in this stand alone environment. If this doesn't work, then it'll narrow down the issue very much.

**Comment by coden965** [comment]
![image](https://github.com/cyberofficial/Synthalingua/assets/77539068/fa6fa89a-7b8f-4907-b2ab-a6375b595333)

**Comment by cyberofficial** [comment]
You you have access to this page? https://download.pytorch.org/whl/cu118

**Comment by coden965** [comment]
![image](https://github.com/cyberofficial/Synthalingua/assets/77539068/90bc0f88-9167-4305-a55c-8a37d95c2f77)
That is what that page shows

**Comment by cyberofficial** [comment]
Okay, can you try this command?

 `nvcc --version`

You should see something like this
![image](https://github.com/cyberofficial/Synthalingua/assets/19499442/c96f58fd-4e79-4ca8-abb4-67bad0cd0d19)

**Comment by coden965** [comment]
![image](https://github.com/cyberofficial/Synthalingua/assets/77539068/86f0f04a-51bc-40eb-b60b-c07983c31dde)

**Comment by cyberofficial** [comment]
Could you try this in the terminal, in the sandboxed environment `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121`

**Comment by coden965** [comment]
Is this what you meant? 
![image](https://github.com/cyberofficial/Synthalingua/assets/77539068/8d01cdc1-b448-46da-9e16-d0e976f59279)

**Comment by cyberofficial** [comment]
You have a newer version of cuda installed so might need to bump the minimum version requirements

**Comment by coden965** [comment]
How would I do that?

**Comment by cyberofficial** [comment]
or might have to require a downgrade of cuda installed if the newest version isn't compatible

**Comment by coden965** [comment]
in the sandbox right?

**Comment by cyberofficial** [comment]
yes

**Comment by coden965** [comment]
![image](https://github.com/cyberofficial/Synthalingua/assets/77539068/1ed8c3e2-d4d0-40ae-962d-831661671c9d)

**Comment by cyberofficial** [comment]
can you do `python -V` for me? and show the full the python version number

**Comment by coden965** [comment]
![image](https://github.com/cyberofficial/Synthalingua/assets/77539068/723e6072-a289-49ae-82e6-9b9b547d28af)

**Comment by cyberofficial** [comment]
needs to be capital V not lower v
you can exit that mode with `quit()`

**Comment by cyberofficial** [comment]
never mind is see the version number forgot the lower v shows it too,

**Comment by coden965** [comment]
![image](https://github.com/cyberofficial/Synthalingua/assets/77539068/ed2b4519-d626-4cbb-81a7-267c780091a2)

**Comment by cyberofficial** [comment]
can you try `pip install torch` in the sandbox and see if that installs

**Comment by coden965** [comment]
![image](https://github.com/cyberofficial/Synthalingua/assets/77539068/be94a1d3-0048-49bb-8d34-2cb2b65c35fa)

**Comment by cyberofficial** [comment]
can you try the pip upgrade command it shows, then retry the command

**Comment by cyberofficial** [comment]
if that fails please try this command 

`python -c "import sys; print(sys.maxsize > 2**32)"`

**Comment by coden965** [comment]
![image](https://github.com/cyberofficial/Synthalingua/assets/77539068/5620983e-e141-4a79-887f-62511392fe8a)

**Comment by cyberofficial** [comment]
Okay, this finally solves it. 

You have 32bit python installed. You need python 3.10.9 64bit.


https://www.python.org/ftp/python/3.10.9/python-3.10.9-amd64.exe

**Comment by coden965** [comment]
jesus, that just made me laugh extremely loud such a small mistake, ive gone ahead and downloaded it.

**Comment by cyberofficial** [comment]
Falls on me for not specifying 32bit or 64bit, learning experience for me I guess 😅

make sure the x32 bit is fully removed, and try the original install method

**Comment by coden965** [comment]
Okay, it did run and download some thing however when im opening the setup.bash it gives this error.
![image](https://github.com/cyberofficial/Synthalingua/assets/77539068/f1464f53-b9de-4b68-903a-e553324ff338)

**Comment by cyberofficial** [comment]
you'll need to run setup.exe for windows. setup.bash for linux

**Comment by coden965** [comment]
Yeah i did run the setup.bat just unsure what to do after that

**Comment by cyberofficial** [comment]
did the setup.bat sure success with out any errors?

**Comment by cyberofficial** [comment]
A good install would look like this 

![cmd_35iaYOK06b](https://github.com/cyberofficial/Synthalingua/assets/19499442/849ec350-53ce-45e4-90df-caf75fd57bd0)

**Comment by coden965** [comment]
Yeah the setup.bat seemed to go in fine from what i saw. I've attached an image of what the livetranslation.bat give me. (yes the setup.bat looked the same as that)
![image](https://github.com/cyberofficial/Synthalingua/assets/77539068/7e96b0e8-2e21-4c20-b35a-9839df29ed27)

**Comment by cyberofficial** [comment]
Ah, i see :) that means it's working

I need to update the example file, `--non_english` is a older command, you need to edit the `livetranslation.bat` file with new commands.

I've made a new UI here https://github.com/cyberofficial/Synthalingua/releases/tag/1.0.9997


Or direct download here [Synthalingua_Wrapper_GUI-win-x64_Jan01_24-Build-6.zip](https://github.com/cyberofficial/Synthalingua/releases/download/1.0.9997/Synthalingua_Wrapper_GUI-win-x64_Jan01_24-Build-6.zip) this is the current UI.

Or visit the prelease page https://github.com/cyberofficial/Synthalingua/releases/tag/1.0.9998
 and grab the latest build [Synthalingua_Wrapper_GUI-win-x64_Feb9_24-Build-7.exe](https://github.com/cyberofficial/Synthalingua/releases/download/1.0.9998/Synthalingua_Wrapper_GUI-win-x64_Feb9_24-Build-7.exe)

and extract the main folder like so
![opera_7lV8E71vK3](https://github.com/cyberofficial/Synthalingua/assets/19499442/ecadced8-87e2-4733-9009-dd332ae77a2e)

**Comment by coden965** [comment]
Okay, ill go ahead and just use the wrapper gui what would i do with this?
![image](https://github.com/cyberofficial/Synthalingua/assets/77539068/d12074f3-7251-46e2-86ab-15871e23a2d0)

**Comment by cyberofficial** [comment]
The main program will be called `Synthalingua_Wrapper.exe`

![Synthalingua_Wrapper_oWyeVvk3cK](https://github.com/cyberofficial/Synthalingua/assets/19499442/a65e3b21-ac98-4edd-a672-a1aa557115d0)

Search for the `transcribe_audio.py`
![Synthalingua_Wrapper_PMko9RCzgc](https://github.com/cyberofficial/Synthalingua/assets/19499442/8c489e96-e330-4d42-a174-81a8b1f50c86)

then choose microphone or HLS (default)
choose your gpu card's video ram size, stream language, then in stream url get a video stream (not video, needs to be live stream) click generate then run 

You can check the video here https://github.com/cyberofficial/Synthalingua/discussions/81 for extra instructions

**Comment by cyberofficial** [comment]
If you have have stuff like twitch prime, or twitch subs, or youtube premium https://github.com/cyberofficial/Synthalingua/tree/bleeding-under-work?tab=readme-ov-file#cookies you can check out how to use cookies to avoid ads

**Comment by coden965** [comment]
Okay i got everything however whenever i press generate and then run cmd pops up super fast which is pretty much unreadable

**Comment by cyberofficial** [comment]
can you show me the gui?

**Comment by coden965** [comment]
![image](https://github.com/cyberofficial/Synthalingua/assets/77539068/bc520121-3f13-4dfd-a14d-1eaaf7ab0135)

**Comment by cyberofficial** [comment]
you'll need to make sure the microphone settings are set up correctly

You can check out my corny video here on how to set up audio passthrough aith voicemeeter

https://streamable.com/mx3gx1

otherwise, you'll need a live link in the stream url

**Comment by coden965** [comment]
I did try it with a stream link however the samething happened

**Comment by cyberofficial** [comment]
![opera_Hf9zKXDlAf](https://github.com/cyberofficial/Synthalingua/assets/19499442/4f1b2034-6930-402c-be6b-46b19bdc428e)
 make sure you have one these options enabled too

**Comment by coden965** [comment]
Yeah even with just one of them or both of them still no luck

**Comment by cyberofficial** [comment]
and you clicked HLS on the top left too?

**Comment by coden965** [comment]
i got it fixed

**Comment by cyberofficial** [comment]
https://github.com/cyberofficial/Synthalingua/assets/19499442/e02eb3df-334b-4bb4-9748-6b632d43a9bd

You can also copy and paste each line from the command block into any command prompt too to debug it

**Comment by coden965** [comment]
The error i had i would assume is it being in far too many folders and i guess the program was just confused idk how to word it

**Comment by cyberofficial** [comment]
i see, windows has a char limit on name and folder lengths, something I can not fix, requires user tweaking, i can probably add a warning or something , but it varies per machine.

**Comment by coden965** [comment]
Well thank you for all the help you have given me everything seems to be working great now.

**Comment by cyberofficial** [comment]
Glad to hear it :D 

If you have any more issues, please feel free to make a new issue.👍
