### ISSUE TITLE
What Is meaning of Linux verified gpu 

### ISSUE THREAD

**Issue by Fabio1shot97** [cyberofficial/Synthalingua#88]
![Screenshot_2024-03-11-17-12-03-091_com android chrome](https://github.com/cyberofficial/Synthalingua/assets/163005807/aee931c6-53b0-4dbd-ac4e-70502ad6db56)

**Comment by cyberofficial** [comment]
It means it's works on Linux with AMD GPUs but not tested on Windows. I do not own a AMD GPU to test with for Windows. Through the Community though it was tested on Linux and verified to work.

**Comment by cyberofficial** [comment]
Though you really don't need a GPU to use the program, the program can use just the cpu, being slower.
